[project]
name = "marl_incentives"
version = "0.1.0"
description = "Packages for the MARL incentives algorithm."
authors = [{name = "Germán Pardo González"}]
requires-python = ">=3.8"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


